import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { ConfigSettings } from "./ConfigSettings";
import { writeFile } from "@session/services/apiAdapt";
import { useLayoutStore } from "@session/stores/useLayoutStore";
import { cancelSessionNavigation, confirmSessionNavigation, useSessionNavigationGuard } from "@session/services/sessionNavigationGuard";
vi.mock("@session/services/apiAdapt", () => ({ getCodexHome: async () => "/fixture", readTextFile: async () => "original", writeFile: vi.fn() }));
vi.mock("@session/features/files", () => ({ CodeEditor: ({ content, onContentChange, onSave }: {content: string; onContentChange: (s: string) => void; onSave: (s: string) => Promise<void>}) => <><textarea aria-label="配置草稿" value={content} onChange={e => onContentChange(e.target.value)} /><button onClick={() => void onSave(content).catch(() => {})}>保存配置</button></> }));
beforeEach(() => {
  vi.mocked(writeFile).mockReset();
  useLayoutStore.setState({ view: "settings" });
  useSessionNavigationGuard.setState({ pending: null });
});
it("loading a saved config is clean, edits block page changes, cancellation preserves text and explicit discard leaves", async () => {
  render(<ConfigSettings />);
  const input = screen.getByRole("textbox", { name: "配置草稿" });
  await waitFor(() => expect((input as HTMLTextAreaElement).value).toBe("original"));
  expect(useSessionNavigationGuard.getState().dirty).toBe(false);
  fireEvent.change(input, { target: { value: "edited" } });
  act(() => useLayoutStore.getState().setView("agent"));
  expect(useLayoutStore.getState().view).toBe("settings");
  expect(useSessionNavigationGuard.getState().pending).toBeTruthy();
  act(cancelSessionNavigation);
  expect((input as HTMLTextAreaElement).value).toBe("edited");
  act(() => useLayoutStore.getState().setView("plugins"));
  act(confirmSessionNavigation);
  expect(useLayoutStore.getState().view).toBe("plugins");
  expect(writeFile).not.toHaveBeenCalled();
});
it("a save acknowledgement cannot mark a newer edit saved or overwrite it; save failures remain guarded", async () => {
  let resolve!: () => void;
  vi.mocked(writeFile).mockImplementationOnce(() => new Promise<void>(r => { resolve = r; }));
  render(<ConfigSettings />);
  const input = screen.getByRole("textbox", { name: "配置草稿" });
  await waitFor(() => expect((input as HTMLTextAreaElement).value).toBe("original"));
  fireEvent.change(input, { target: { value: "first edit" } });
  fireEvent.click(screen.getByRole("button", { name: "保存配置" }));
  fireEvent.change(input, { target: { value: "newer edit" } });
  act(() => useLayoutStore.getState().setView("agent"));
  act(confirmSessionNavigation);
  expect(useLayoutStore.getState().view).toBe("settings");
  await act(async () => resolve());
  expect((input as HTMLTextAreaElement).value).toBe("newer edit");
  expect(useSessionNavigationGuard.getState().dirty).toBe(true);
  act(cancelSessionNavigation);
  vi.mocked(writeFile).mockRejectedValueOnce(new Error("isolated save error"));
  fireEvent.click(screen.getByRole("button", { name: "保存配置" }));
  await screen.findByText("isolated save error");
  expect(useSessionNavigationGuard.getState().dirty).toBe(true);
  expect(useSessionNavigationGuard.getState().saving).toBe(false);
});
